### ISSUE TITLE
Error: Method “simulate” is only meant to be run on a single node. 0 found instead.

### ISSUE THREAD

**Issue by aisayo** [learn-co-curriculum/react-updating-state-lab#10]
If a student is receiving this error, check that inside their JSX, `className` is defined correctly

**Comment by lpzraf** [comment]
To the students please do not confuse declaring a class for React with html/css. 
Use <button className=  
instead of class=

**Comment by maxwellbenton** [comment]
Hi @aisayo and @lpzraf,

Thank you for this feedback. We've updated this lesson to include additional information on using `className` instead of `class`, which should help prevent this issue from occuring in the future.

Thank you both for contributing!
