### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by AubreyNeimeier** [learn-co-curriculum/react-updating-state-lab#11]
The curriculum states the spread operator is recommended so I think the solution should prioritize that solution, rather than the object.assign(). 

Also, the solution for updating the digital clicker is MUCH MORE COMPLEX than necessary, and includes life-cycle components, even tho that is 2 sections ahead. 
solution should be: 
handleClick = () => {
    this.setState({
      timesClicked: ++ this.state.timesClicked
    })
  }

**Comment by maxwellbenton** [comment]
Hi @AubreyNeimeier,

I totally agree about the spread operator and have updated the solution accordingly. Thank you for pointing this out!

In regards to the handleClick solution, it is not recommended that `this.state` is called from within `setState` as there is a possibility that the state changed asynchronously just before. It is better to use the functional version of setState to ensure state doesn't change between the time `setState` is called in your code and when it actually fires asynchronously in a batch
