### ISSUE TITLE
Previous State has not been covered

### ISSUE THREAD

**Issue by kjgenevieve** [learn-co-curriculum/react-updating-state-lab#13]
The idea of grabbing information from a previous state hasn't yet been covered in labs. It should be mentioned, at the very least, and preferably covered explicitly in a ReadMe or lab.

**Comment by maxwellbenton** [comment]
Hi @kjgenevieve,

Thank you for spotting this! We've updated the [previous Readme, Updating State](https://github.com/learn-co-curriculum/react-updating-state) to include a section on accessing previous state using the functional version of `setState`.  This change should provide better context to this lab for future students.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide feedback and to help improve our curriculum!

Thank you!
