### ISSUE TITLE
Routes to wrong 'Next' lab

### ISSUE THREAD

**Issue by Samuel-DeSantis** [learn-co-curriculum/react-updating-state-lab#18]
### Canvas Link

https://learning.flatironschool.com/courses/1883/assignments/125708?module_item_id=259621

### Concern

Clicking 'Next' skips over the 'React Controlled Components' code-a-long lab.

### Additional Context

Not sure if it is buggy on my end but I refreshed the page and tried it a couple times and it keeps skipping the lab. I didn't realize I skipped it till I completed the lab before the reading and code-a-long.

### Suggested Changes

Adjust link so that it connects to the proper lab.

**Comment by lizbur10** [comment]
Hi @Samuel-DeSantis ! Thanks for bringing this to our attention. The issue should now be fixed, so I'm going to go ahead and close this issue. Please feel free to reopen it if it's still not working for you.

Thanks for contributing to the Flatiron School curriculum 💙
