### ISSUE TITLE
In DigitalClicker.js: ++this.state.timesClicked mutates directly.

### ISSUE THREAD

**Issue by IngridWong0715** [learn-co-curriculum/react-updating-state-lab#7]
In the solution code, it's written`timesClicked: ++this.state.timesClicked`, which basically defeats the purpose of using setState()

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @IngridWong0715 .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
