### ISSUE TITLE
Code snippet incorrect 

### ISSUE THREAD

**Issue by haniffaraz** [learn-co-curriculum/react-updating-state-lab#9]
> This component has several state properties. The initial state shape looks like this: js { errors: [], user: null, settings: { bitrate: 8, video: { resolution: '1080p' } } }

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by haniffaraz** [comment]
Anytime my pleasure.
